version: "3.8"

services:
  fastapi:
    build:
      context: . # Path to the FastAPI project
    container_name: fastapi
    ports:
      - "8001:8001" # Exposing FastAPI on port 8001
    networks:
      - scentmatch-network

networks:
  scentmatch-network:
    driver: bridge
